### ISSUE TITLE
Frage Token

### ISSUE THREAD

**Issue by sigi2345** [Marinek/ioBroker.samsung_2022_tv_adapter#5]
Hallo, wie und wo bekomme ich den REMOTE_NAME
und Token?

Sigi

**Comment by Marinek** [comment]
Hi @sigi2345 ,

den REMOTE_NAME kann man sich frei wählen. Dieses wird auf dem Fernseher später angezeigt unter "verbundene Geräte". Es ist also nur ein Name ohne technische Bedeutung. 

Um einen Token zu erhalten, musst du IP und MAC korrekt in der Konfiguration eingetragen haben. Der Token muss leer sein! Schalte den Fernseher ein. Wenn du den Adapter neu startest, wird er versuchen sich mit dem Fernseher zu verbinden. Auf dem Fernseher popt eine Nachricht auf. Hier muss man den Adapter zulassen.

Anschließend wird der Token automatisch ausgelesen und in der Konfiguration gespeichert. 
Schöne Grüße
Martin

**Comment by sigi2345** [comment]
Ok, funktioniert mit meinen Samsung nicht.

`<html>
<body>


samsung_2022_tv_adapter.0 | 2022-04-15 19:42:17.422 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
samsung_2022_tv_adapter.0 | 2022-04-15 19:42:17.421 | info | terminating
samsung_2022_tv_adapter.0 | 2022-04-15 19:42:17.419 | error | Error send Key
samsung_2022_tv_adapter.0 | 2022-04-15 19:42:17.418 | error | Error: Error send Key at C:\Program Files\iobroker\Home\node_modules\samsung-tv-control\lib\samsung.js:55:23 at WebSocket.<anonymous> (C:\Program Files\iobroker\Home\node_modules\samsung-tv-control\lib\samsung.js:289:17) at WebSocket.emit (events.js:400:28) at emitErrorAndClose (C:\Program Files\iobroker\Home\node_modules\samsung-tv-control\node_modules\ws\lib\websocket.js:874:13) at ClientRequest.<anonymous> (C:\Program Files\iobroker\Home\node_modules\samsung-tv-control\node_modules\ws\lib\websocket.js:736:5) at ClientRequest.emit (events.js:400:28) at TLSSocket.socketErrorListener (_http_client.js:475:9) at TLSSocket.emit (events.js:400:28) at emitErrorNT (internal/streams/destroy.js:106:8) at emitErrorCloseNT (internal/streams/destroy.js:74:3) at processTicksAndRejections (internal/process/task_queues.js:82:21)
samsung_2022_tv_adapter.0 | 2022-04-15 19:42:17.418 | error | uncaught exception: Error send Key
samsung_2022_tv_adapter.0 | 2022-04-15 19:42:14.901 | info | config REMOTE_NAME: Samsung
samsung_2022_tv_adapter.0 | 2022-04-15 19:42:14.901 | info | config MAC: 24:4B:03:4B:AA:3F
samsung_2022_tv_adapter.0 | 2022-04-15 19:42:14.901 | info | config IP: 192.168.178.51
samsung_2022_tv_adapter.0 | 2022-04-15 19:42:14.893 | info | starting. Version 0.2.1 (non-npm: Marinek/ioBroker.samsung_2022_tv_adapter#8dc49039400f910db0f41f66c1a5e332b96edf36) in C:/Program Files/iobroker/Home/node_modules/iobroker.samsung_2022_tv_adapter, node: v14.19.1, js-controller: 4.0.21


</body>
</html>`

**Comment by Marinek** [comment]
Ja, das sieht so aus tatsächlich. Die Fehlermeldung kommt von den "unterliegenden" API, die ich nur verwende. Leider gibt es da keine abschließende Liste von unterstützen Geräten. 

Der Kollege auf https://github.com/Toxblh/samsung-tv-control schreibt: Tested with Samsung UE43NU7400 and UN55NU7100

Wie alt ist den der Fernseher?

**Comment by sigi2345** [comment]
> Ja, das sieht so aus tatsächlich. Die Fehlermeldung kommt von den "unterliegenden" API, die ich nur verwende. Leider gibt es da keine abschließende Liste von unterstützen Geräten.
> 
> Der Kollege auf https://github.com/Toxblh/samsung-tv-control schreibt: Tested with Samsung UE43NU7400 and UN55NU7100
> 
> Wie alt ist den der Fernseher?

2015

**Comment by Marinek** [comment]
Die hier verwendete API wird erst ab 2016 in den Fernsehern verwendet =(

Sorry.
